Pin fog-openstack library to avoid breakage
The update of the fog-openstack ruby gem from 0.12.7 to 0.2.0 breaks
Chef recipes. The first call to cookbook-openstackclient from
cookbook-openstack-identity:recipes/registration.rb fails already with
something like (extract from a kitchen run of openstack-chef-repo):

  ERROR: openstack_domain[default] (openstack-identity::registration line 69)
  had an error: Fog::Identity::OpenStack::NotFound: Expected([200]) <=>
  Actual(404 Not Found)

  (http://127.0.0.1:35357/v3/v3/domains): The resource could not be found.

Change-Id: I4d30cb1770b6774b39bfd4e4c413f25816b405df
(cherry picked from commit 7ae001c6c4831abae5e26a811e27f6f1c4c15027)